name: GitHub Actions Test
on: [push] # Code တစ်ခုခု ပြင်တိုင်း စလုပ်မယ်

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: My First Step
        run: echo "GitHub Actions is now working successfully!"
